# Generated by Django 6.1.1 on 2026-10-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='estoque',
            field=models.IntegerField(),
        ),
    ]
