# Generated by Django 6.1.1 on 2026-10-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0002_alter_planta_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='image_url',
            field=models.TextField(default=''),
        ),
    ]
